-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀

-- █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

-- Set your personal hyprland configuration here

-- for sample file, please refer https://github.com/prasanthrangan/hyprdots/blob/main/Configs/.config/hypr/userprefs.t2

hl.config({
    debug = {
        disable_logs = true,
    },
})

hl.env("WLR_NO_HARDWARE_CURSORS", 1)

hl.env("QT_DEVICE_PIXEL_RATIO", 0)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

hl.env("QT_SCREEN_SCALE_FACTORS", 1)

hl.env("QT_SCALE_FACTOR", 1)

--  ___                 _            ___              

-- | __|_ _____ __ _  _| |_ ___ ___ / _ \ _ _  __ ___ 

-- | _|\ \ / -_) _| || |  _/ -_)___| (_) | ' \/ _/ -_)

-- |___/_\_\___\__|\_,_|\__\___|    \___/|_||_\__\___|



-- exec-once = ~/.config/hypr/scripts/sleep.sh


--exec-once = kitty --class HeadlessKitty --single-instance --listen-on unix:/tmp/kitty-socket tail -f /dev/null

hl.window_rule({
    name  = "windowrule-1",
    match = {
        class = "HeadlessKitty",
    },
    workspace = { "special:headless", "silent" },
})


hl.plugin("hyprbars", function()
    -- example config
    bar_height = 20,
    -- example buttons (R -> L)
    -- hyprbars-button = color, size, on-click
    hyprbars-button = { "rgb(ff4040)", 20, "󰖭", "hyprctl dispatch killactive" },
    hyprbars-button = { "rgb(eeee11)", 20, "", "hyprctl dispatch fullscreen 1" },
    bar_color = "rgb(000000)",
end)
hl.plugin("dynamic-cursors", function()
    enabled = true,
    -- sets the cursor behaviour, supports these values:
    -- tilt   - tilt the cursor based on x-velocity
    -- rotate - rotate the cursor based on movement direction
    -- stretch - stretch the cursor shape based on direction and velocity
    -- none   - do not change the cursors behaviour
    mode = "stretch",
end)

-- plugin = /usr/lib/libhycov.soxxx

-- plugin {

--     hycov {

--         overview_gappo = 60 # gaps width from screen edge

--         overview_gappi = 24 # gaps width from clients

--         enable_hotarea = 0 # enable mouse cursor hotarea, when cursor enter hotarea, it will toggle overview    

--         hotarea_monitor = all # monitor name which hotarea is in, default is all

--         hotarea_pos = 1 # position of hotarea (1: bottom left, 2: bottom right, 3: top left, 4: top right)

--         hotarea_size = 10 # hotarea size, 10x10

--         swipe_fingers = 4 # finger number of gesture,move any directory

--         move_focus_distance = 100 # distance for movefocus,only can use 3 finger to move 

--         enable_gesture = 0 # enable gesture

--         disable_workspace_change = 0 # disable workspace change when in overview mode

--         disable_spawn = 0 # disable bind exec when in overview mode

--         auto_exit = 1 # enable auto exit when no client in overview

--         auto_fullscreen = 0 # auto make active window maximize after exit overview

--         only_active_workspace = 0 # only overview the active workspace

--         only_active_monitor = 0 # only overview the active monitor

--         enable_alt_release_exit = 1 # alt swith mode arg,see readme for detail

--         alt_toggle_auto_next = 0 # auto focus next window when toggle overview in alt swith mode

--         #alt_replace_key = Alt_L # alt swith mode arg,see readme for detail

--         click_in_cursor = 1 # when click to jump,the target windwo is find by cursor, not the current foucus window.

--         hight_of_titlebar = 0 # height deviation of title bar hight

-- 

--     }

-- }

-- electron apps (vsode)

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█

-- █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄

-- See https://wiki.hyprland.org/Configuring/Monitors/

--monitor = ,preferred,auto,auto

--monitor = eDP-1,1920x1200@60,auto,1

--monitor = HDMI-A-1,preferred,auto,auto

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1200@60",
    position = "auto",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "preferred",
    position = "auto-left",
    scale    = "auto",
})

-- My seat

--monitor = desc:Philips Consumer Electronics Company PHL 276E8V 0x00000295, preffered, auto-right, 1.5

-- CF's seat

--monitor = desc:Dell Inc. DELL U3818DW 5KC0391V06WL, 2560x1080@60.00Hz, auto-left, auto

-- Johnny's seat

--monitor = desc:Dell Inc. DELL U2722D 65Y0193, preferred, -640x-1440, auto

--monitor = desc:Dell Inc. DELL U2722D 91Y0193, 2560x1440@59.95Hz, auto, auto, transform, 3

-- Nuclear

--monitor = desc:BNQ BenQ GL2760 E8H04910019, preferred, auto-left, 1

-- █ █▄░█ █▀█ █░█ ▀█▀

-- █ █░▀█ █▀▀ █▄█ ░█░

hl.config({
    input = {
        kb_layout = false,
        follow_mouse = 2,
        float_switch_override_focus = 0,
        repeat_rate = 60,
        repeat_delay = 400,
        touchpad = {
            natural_scroll = true,
            scroll_factor = 0.2,
        },
        sensitivity = -0.125,
        -- -1.0 - 1.0, 0 means no modification.
        -- force_no_accel = true
        accel_profile = "adaptive",
        tablet = {
            output = "eDP-1",
        },
        touchdevice = {
            output = "eDP-1",
        },
        numlock_by_default = true,
    },
})

hl.config({
    misc = {
        focus_on_activate = true,
        disable_watchdog_warning = true,
    },
})

hl.device({
    name = "elan327e:00-04f3:327e-touchpad",
    sensitivity = 0,
})

hl.device({
    name = "elan327e:00-04f3:327e-mouse",
    sensitivity = 0,
})

hl.device({
    name = "logitech-mx-master-3-1",
    sensitivity = -0.4,
    accel_profile = "adaptive",
})

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

-- general {

-- 	sensitivity = 0.65

-- }

-- █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀

-- █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█

-- Unbind must be before bind

hl.unbind("F10")

-- toggle audio mute

hl.unbind("F11")

-- decrease volume

hl.unbind("F12")

-- increase volume

hl.unbind("$mainMod" .. " + " .. "K")

-- change keyboard layout

hl.unbind("$mainMod" .. " + " .. "T")

-- open terminal

hl.unbind("$mainMod" .. " + " .. "A")

-- launch desktop applications

hl.unbind("$mainMod" .. " + " .. "G")

-- toggle the window on focus to float

hl.unbind("$mainMod + ALT" .. " + " .. "left")

-- previous wallpaper

hl.unbind("$mainMod + ALT" .. " + " .. "right")

-- next wallpaper

hl.unbind("$mainMod" .. " + " .. "F")

-- open browser

-- unbind = $mainMod, S, togglespecialworkspace,

hl.unbind("ALT" .. " + " .. "Tab")

hl.unbind("Super" .. " + " .. "Z")

hl.unbind("$mainMod+Alt" .. " + " .. "Right")

-- next wallpaper

hl.unbind("$mainMod+Alt" .. " + " .. "Left")

-- previous wallpaper

hl.unbind("Ctrl+Shift" .. " + " .. "Escape")

hl.unbind("$mainMod" .. " + " .. "L")

hl.unbind("$mainMod" .. " + " .. "B")

hl.unbind("$mainMod" .. " + " .. "C")

hl.unbind("$mainMod" .. " + " .. "DELETE")

-- Binds

-- bind = $mainMod SHIFT, L, exec, ~/.config/hypr/scripts/quick_sleep.sh

-- bind = $mainMod SHIFT, L, exec,  ~/.local/share/bin/auto_hyprlock_theme.sh

hl.bind("$mainMod" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock & disown"))

hl.bind("$mainMod" .. " + " .. "F", hl.dsp.exec_cmd("vivaldi"))

-- open Vivaldi browser

hl.bind("$mainMod" .. " + " .. "K", hl.dsp.exec_cmd("$scrPath/dontkillsteam.sh"))

-- killactive, kill the window on focus

hl.bind("$mainMod" .. " + " .. "RETURN", hl.dsp.exec_cmd("kitty"))

---1  # open terminal

--bind = $mainMod, RETURN, exec, /home/oskar/repos/scripts/kitty_launch.sh  # open terminal

hl.bind("$mainMod" .. " + " .. "SPACE", hl.dsp.exec_cmd("pkill -x rofi || $scrPath/rofilaunch.sh d"))

-- launch desktop applications

hl.bind("$mainMod" .. " + " .. "B", hl.dsp.exec_cmd("Hyde show binds"))

-- Shows Keybindings

hl.bind("$mainMod" .. " + " .. "G", hl.dsp.exec_cmd("geogebra"))

-- Open GeoGebra

hl.bind("$mainMod" .. " + " .. "Z", hl.dsp.exec_cmd("zathura"))

-- Open GeoGebra

-- bind = $mainMod, S, exec, spotify # Open Spotify

hl.bind("$mainMod + SHIFT" .. " + " .. "S", hl.dsp.workspace.toggle_special(nil))

-- Toggle special workspace

--bind = ALT,Tab,hyprspace:overview,toggle # Show workspace overview

-- bind=ALT,left,hycov:movefocus,l

-- bind=ALT,right,hycov:movefocus,r

-- bind=ALT,up,hycov:movefocus,u

-- bind=ALT,down,hycov:movefocus,d

hl.bind("$mainMod + ALT" .. " + " .. "right", hl.dsp.focus("+1"))

-- Moves focus from monitor n to n+1

hl.bind("$mainMod + ALT" .. " + " .. "left", hl.dsp.focus(-1))

-- Moves focus from monitor n to n-1

--bind = $mainMod, M, exec, thunderbird -compose # Write new mail

hl.bind("$mainMode" .. " + " .. "C", hl.dsp.exec_cmd("code"))

-- Open vscode 

hl.bind("$mainMode + SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("code -n"))

-- Open new vscode instance 

hl.bind("Ctrl+Shift" .. " + " .. "Escape", hl.dsp.exec_cmd("kitten quick-access-terminal --config ~/.config/kitty/quick_access_terminal.conf btop"))

hl.bind("ALT" .. " + " .. "Tab", hl.dsp.window.cycle_next())

hl.bind("SHIFT + ALT" .. " + " .. "Tab", hl.dsp.window.cycle_next({ next = false }))

hl.bind("$mainMod + CONTROL" .. " + " .. 1, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 1 current"))

-- Move workspace  1  to current monitor 

hl.bind("$mainMod + CONTROL" .. " + " .. 2, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 2 current"))

-- Move workspace  2  to current monitor

hl.bind("$mainMod + CONTROL" .. " + " .. 3, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 3 current"))

-- Move workspace  3  to current monitor

hl.bind("$mainMod + CONTROL" .. " + " .. 4, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 4 current"))

-- Move workspace  4  to current monitor

hl.bind("$mainMod + CONTROL" .. " + " .. 5, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 5 current"))

-- Move workspace  5  to current monitor

hl.bind("$mainMod + CONTROL" .. " + " .. 6, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 6 current"))

-- Move workspace  6  to current monitor

hl.bind("$mainMod + CONTROL" .. " + " .. 7, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 7 current"))

-- Move workspace  7  to current monitor

hl.bind("$mainMod + CONTROL" .. " + " .. 8, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 8 current"))

-- Move workspace  8  to current monitor

hl.bind("$mainMod + CONTROL" .. " + " .. 9, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 9 current"))

-- Move workspace  9  to current monitor

hl.bind("$mainMod + CONTROL" .. " + " .. 0, hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 10 current"))

-- Move workspace 10  to current monitor

hl.bind("$mainMod + ALT + SHIFT" .. " + " .. "right", { direction = "mon:+1" })

-- Move window to next monitor

hl.bind("$mainMod + ALT + SHIFT" .. " + " .. "left", { direction = "mon:-1" })

-- Move window to previous monitor

hl.bind("$mainMod" .. " + " .. "period", hl.dsp.exec_cmd("Hyde show emoji"))

-- Emoji Picker

hl.bind("$mainMod + SHIFT" .. " + " .. "period", hl.dsp.exec_cmd("Hyde show glyph"))

-- Glyph Picker

hl.bind("CONTROL" .. " + " .. "ESCAPE", hl.dsp.exec_cmd("Hyde show calc"))

hl.bind("$mainMod" .. " + " .. "R", hl.dsp.exec_cmd("hydectl reload"))

hl.bind("ALT" .. " + " .. "RETURN", hl.dsp.exec_cmd("hyprctl dispatch fullscreen"))

-- Toggle floating on focused window

hl.bind("$mainMod + ALT" .. " + " .. "mouse:272", hl.dsp.window.resize(), { mouse = true })

hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("hyprlock & disown && sleep 5 && systemctl suspend"), { locked = true })

-- bindl= , switch:on:Lid Switch, exec, swaylock -f -c 000000 && sleep 5 && systemctl suspend

-- __      ___         _              ___      _        

-- \ \    / (_)_ _  __| |_____ __ __ | _ \_  _| |___ ___

--  \ \/\/ /| | ' \/ _` / _ \ V  V / |   / || | / -_|_-<

--   \_/\_/ |_|_||_\__,_\___/\_/\_/  |_|_\\_,_|_\___/__/

-- animations {

--     enabled = true

--     bezier = linear, 0, 0, 1, 1

--     bezier = md3_standard, 0.2, 0, 0, 1

--     bezier = md3_decel, 0.05, 0.7, 0.1, 1

--     bezier = md3_accel, 0.3, 0, 0.8, 0.15

--     bezier = overshot, 0.05, 0.9, 0.1, 1.1

--     bezier = crazyshot, 0.1, 1.5, 0.76, 0.92 

--     bezier = hyprnostretch, 0.05, 0.9, 0.1, 1.0

--     bezier = fluent_decel, 0.1, 1, 0, 1

--     bezier = easeInOutCirc, 0.85, 0, 0.15, 1

--     bezier = easeOutCirc, 0, 0.55, 0.45, 1

--     bezier = easeOutExpo, 0.16, 1, 0.3, 1

--     animation = windows, 1, 3, md3_decel, popin 60%

--     animation = border, 1, 1, default

--     animation = fade, 1, 2.5, md3_decel

--     animation = workspaces, 1, 3.5, easeOutExpo, slide

--     animation = specialWorkspace, 1, 3, md3_decel, slidevert

-- }

-- Border size

hl.window_rule({
    name  = "windowrule-2",
    match = {
        class = "(.*)",
    },
    border_size = 5,
})

-- File Explorers

hl.window_rule({
    name  = "windowrule-3",
    match = {
        class = "g.kde.dolphin",
    },
    float = true,
})

hl.window_rule({
    name  = "windowrule-4",
    match = {
        class = "e.dolphin",
    },
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-5",
    match = {
        class = "([Xx]dg-desktop-portal-*)",
        title = "([Oo]pen [Ff]ile)",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-6",
    match = {
        class = "[Xx]dg-desktop-portal-gtk",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-7",
    match = {
        class = "[Xx]dg-desktop-portal-lxqt",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-8",
    match = {
        class = "com.system76.CosmicFilesDialog",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-9",
    match = {
        class = "desktop.impl.portal.desktop.kde",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-10",
    match = {
        class = "(Vivaldi-stable)",
        title = "(Open File)",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-11",
    match = {
        class = "(Vivaldi-stable)",
        initial_title = "(Vivaldi Settings:General- Vivaldi)",
    },
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-12",
    match = {
        class = "([Cc]ode)",
        title = "(Open File)",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-13",
    match = {
        class = "code",
    },
    suppress_event = "fullscreen",
})

hl.window_rule({
    name  = "windowrule-14",
    match = {
        class = "([Cc]ode)",
        title = "(Open Folder)",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-15",
    match = {
        class = "([Cc]ode)",
        float = 1,
    },
    center = true,
    allows_input = true,
})

hl.window_rule({
    name  = "windowrule-16",
    match = {
        class = "([Cc]ode)",
        title = "(Open.*)",
    },
    allows_input = true,
})

hl.window_rule({
    name  = "windowrule-17",
    match = {
        class = "(Vivaldi.*)",
        title = "(Open.*)",
    },
    allows_input = true,
})

hl.window_rule({
    name  = "windowrule-18",
    match = {
        class = "(org.pulseaudio.pavucontrol)",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

-- Vivaldi Settings Window

hl.window_rule({
    name  = "windowrule-19",
    match = {
        title = "(Vivaldi Settings:General- Vivaldi)",
    },
    float = true,
    center = true,
    size = { "(monitor_w*0.6)", "(monitor_h*0.6)" },
})

hl.window_rule({
    name  = "windowrule-20",
    match = {
        class = "vivaldi-stable",
    },
    suppress_event = "fullscreen",
})

-- Catch-all floating

--windowrule = allowsinput, floating:1

--windowrule = center, floating:1

-- Transparency

-- First number is active, second is inactive

hl.window_rule({
    name  = "windowrule-21",
    match = {
        class = "negative:(vivaldi-stable|firefox|Microsoft-edge|Brave-browser)",
    },
    opacity = { 0.9, "override", 0.75, "override" },
})

--windowrule = opacity 0.9 0.75, class:?!(vivaldi-stable|firefox|Microsoft-edge|Brave-browser)

-- Matplotlib

hl.window_rule({
    name  = "windowrule-22",
    match = {
        class = "(matplotlib|python3)",
        title = "(Figure )(\\d*)",
    },
    float = true,
    size = { "(monitor_w*0.5)", "(monitor_h*0.5)" },
    move = { "((monitor_w*1)-window_w-10)", "(73)" },
})

--# Relative

--windowrule=move 100%-w-0.5% 1%, class:(matplotlib|python3), title:(Figure )(\d*)

--# Absolute

--## No bar

--windowrule=move 100%-w-10 10, class:(matplotlib|python3), title:(Figure )(.\d*)

--## With bar

--# Add plot at cursor position

--windowrule=move cursor -50% -50%, class:(matplotlib|python3), title:(Figure )(\d*)

-- Hyprbars

-- #windowrule = plugin:hyprbars:nobar, class:^(matplotlib|python3), title:^(Figure )(\d*)

hl.window_rule({
    name  = "windowrule-23",
    match = {
        float = 0,
    },
    hyprbars:no_bar = true,
})

-- Screenshot

hl.window_rule({
    name  = "windowrule-24",
    match = {
        class = "(swappy)",
    },
    allows_input = true,
})

-- File manger

hl.window_rule({
    name  = "windowrule-25",
    match = {
        class = "org.kde.dolphin",
    },
    float = true,
    size = { "(monitor_w*0.5)", "(monitor_h*0.5)" },
})

-- No Auto Fullscreen

--windowrule = suppressevent maximize, class:(Vivaldi-stable)

--windowrule = suppressevent fullscreen, class:(Vivaldi-stable)

--windowrule = fullscreen:1, class:(Code)

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("kanshi")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ on")
end)
